import { Inter } from "next/font/google";
import "./globals.css";
import { AppShellFooter, MantineProvider, createTheme } from "@mantine/core";
import '@mantine/core/styles.css';




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "VoiceTour Navigator",
  description: "Generated by create next app",
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({ children }) {
const myStyles = {
  backgroundColor: '#2234ae',
backgroundImage: 'linear-gradient(180deg, #2234ae 0%, #191714 50%)'
}

  return (
    <html lang="en">

      <body className={inter.className}>
        <MantineProvider theme={theme} defaultColorScheme="dark">
         <div style={myStyles}>
         {children}
         </div>
          
        </MantineProvider>
      </body>
    </html>
  );
}
