import { Inter } from "next/font/google";
import "./globals.css";
import { AppShellFooter, MantineProvider, createTheme } from "@mantine/core";
import '@mantine/core/styles.css';




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "VoiceTour Navigator",
  description: "Generated by create next app",
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({ children }) {
const myStyles = {

  backgroundColor:' #166d3b',
backgroundImage:' linear-gradient(147deg, #166d3b 0%, #000000 74%)'
}

  return (
    <html lang="en">

      <body className={inter.className}>
        <MantineProvider theme={theme} defaultColorScheme="dark">
         <div style={myStyles}>
         {children}
         </div>
          
        </MantineProvider>
      </body>
    </html>
  );
}
